# .github/workflows/test.yml
name: Test Custom Action

on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run custom action
        uses: ./.github/actions/my-action
        with:
          name: "GitHub User"
